Repository semantic-release/semantic-release, pull requests merged in 2018-11, with the labels that each got.

#978 style: fix prettier errors
  lib/plugins/index.js
Labels: core, in progress

#981 Update FAQ
  docs/support/FAQ.md
Labels: docs, in progress

#983 feat: support multiple plugins for the `analyzeCommits` step
  docs/usage/plugins.md
  lib/definitions/constants.js
  lib/definitions/errors.js
  lib/definitions/plugins.js
  lib/plugins/index.js
  lib/plugins/utils.js
  test/definitions/plugins.test.js
  test/plugins/plugins.test.js
  test/plugins/utils.test.js
Labels: core, feature, in progress

#986 docs/resources: fix quote marks
  docs/support/resources.md
Labels: docs

#989 docs: add Codefresh in list of CIs with pipelines
  docs/usage/ci-configuration.md
Labels: docs, in progress

#994 fix: push only tags to remote repo
  lib/git.js
  test/git.test.js
Labels: bug, core, in progress

#1000 fix: correctly resolve plugins installed globally with `npx`
  lib/get-config.js
  test/get-config.test.js
Labels: bug, core, in progress

#1002 docs(configuration.md): tweak grammar [ci skip]
  docs/usage/configuration.md
Labels: docs

#1004 fix: rename default branch
  .travis.yml
  README.md
  bin/semantic-release.js
  codecov.yml
  docs/extending/plugins-list.md
  lib/definitions/errors.js
  package.json
Labels: in progress

#1006 fix: fetch all release branches on CI
  index.js
  lib/branches/index.js
  lib/git.js
  test/branches/branches.test.js
  test/branches/expand.test.js
  test/git.test.js
Labels: bug, core, in progress

#1007 fix: remove unnecessary `branch` parameter from `push` function
  index.js
  lib/git.js
  test/git.test.js
Labels: bug, core, in progress

#1009 fix: remove unnecessary `branch` parameter from `push` function
  index.js
  lib/git.js
  test/git.test.js
Labels: bug, core, in progress

#1012 docs: add maven-semantic-release to list of community plugins
  docs/extending/plugins-list.md
Labels: docs, in progress
