Repository semantic-release/semantic-release, pull requests merged in 2018-08, with the labels that each got.

#883 Update @semantic-release/npm to the latest version 🚀
  package.json
Labels: in progress

#884 fix: do not clone `stdout`/`stderr` passed to pugins
  index.js
  lib/plugins/normalize.js
  test/plugins/normalize.test.js
Labels: bug, core, in progress

#885 docs(plugins): add semantic-release-firefox
  docs/extending/plugins-list.md
Labels: docs, in progress

#889 fix: do not convert ssh `repositoryUrl` to https
  lib/get-git-auth-url.js
  test/get-git-auth-url.test.js
Labels: bug, core, in progress

#894 Revert "fix: do not convert ssh `repositoryUrl` to https"
  lib/get-git-auth-url.js
  test/get-git-auth-url.test.js
Labels: bug, core, in progress

#900 test: use real writable stream
  package.json
  test/index.test.js
  test/integration.test.js
Labels: core, in progress

#910 fix: hide sensitive data in relesae notes and `fail`/`success` plugin params
  lib/definitions/plugins.js
  lib/hide-sensitive.js
  lib/plugins/index.js
  lib/utils.js
  test/definitions/plugins.test.js
  test/index.test.js
Labels: bug, core, in progress
