Repository semantic-release/semantic-release, pull requests merged in 2018-10, with the labels that each got.

#937 docs: add Waffle.io README badge
  README.md
Labels: docs, in progress

#942 Fix error messages
  lib/definitions/errors.js
  lib/verify.js
Labels: bug, core, in progress

#947 docs: Correct spelling of false
  docs/usage/configuration.md
Labels: docs

#948 fix: use module name in logs for plugins loaded with `plugins` option
  lib/plugins/index.js
  lib/plugins/normalize.js
  lib/plugins/utils.js
  test/plugins/plugins.test.js
Labels: bug, core, in progress

#949 fix: fix logs for plugins loaded with `plugins` option
  lib/plugins/index.js
Labels: bug, core, in progress

#953 fix: do not log outated branch error for missing permission cases
  index.js
  lib/git.js
Labels: bug, core, in progress

#955 docs: add semantic-release-expo to plugins list
  docs/extending/plugins-list.md
Labels: docs

#961 feat: Return release notes on nextRelease even if running on dry mode
  index.js
Labels: bug, core

#967 fix: remove dependency to `git-url-parse`
  lib/get-git-auth-url.js
  package.json
  test/get-git-auth-url.test.js
  test/index.test.js
Labels: bug, core, in progress
